import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faGithub, faDev, faCodepen } from "@fortawesome/free-brands-svg-icons";
import { faBurger } from "@fortawesome/free-solid-svg-icons";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Simone Puhl · Com</title>
        <meta
          name="description"
          content="Awesomely generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Simone Puhl</h1>
        <h4 className="tag-phrase">
        Front-end developer wanting to make pretty things online. 
        Currently dealing with Magento2  <a href="https://www.experius.nl/">@experius</a>. 
        Also I love #EC5800.
</h4>
        <div>
          <Link href='/about'>About / </Link>
          <Link href='/projects'>Projects / </Link>
          <Link href='/uses'>Uses</Link>
        </div>
        {/* fix this later when I do styling */}
        <br />
        <div>
            <a href="https://github.com/persimone">·&ensp;
              <FontAwesomeIcon icon={faGithub} /> ·&ensp;
            </a>
            <a href="https://dev.to/persimone">
              <FontAwesomeIcon icon={faDev} /> ·&ensp;
            </a>
            <a href="https://codepen.io/persimone">
              <FontAwesomeIcon icon={faCodepen} /> ·
            </a>
          </div>
        <section>

          <h3 className="tag-phrase section-title">
            This is the homepage, pretty cool ey?!
          </h3>
          <p className="section-body">
            Lorem, ipsum dolor sit amet consectetur adipisicing elit.
            Aspernatur culpa expedita beatae distinctio sunt unde tempora nemo
            aliquam nostrum dolor id optio blanditiis, molestias tempore
            autem? Rem, tempore. Architecto, voluptatum?
          </p>

          <section id="contact">
            <h3 className="section-title">Contact Us</h3>
            <p className="section-body">
              You can Contact us via our various social media handles
            </p>
          </section>
        </section>
      </main>

      <footer className={styles.footer}>
        Powered by{" "} &ensp;
        <FontAwesomeIcon icon={faBurger} />
      </footer>
    </div>
  );
}
